object Versions {
    const val coreKtx = "1.9.0"
    const val activityCompose = "1.8.1"
    const val composeUi = "1.5.1"
    const val composeMaterial = "1.3.1"
    const val composeToolingPreview = "1.5.1"
    const val navigationCompose = "2.7.5"
    const val navigationAnimation = "0.24.12-rc"
    const val composeBom = "2025.01.01"
    const val lifecycleViewModelCompose = "2.6.2"
    const val lifecycleRuntimeKtx = "2.7.0"
    const val koinAndroid = "3.5.0"
    const val koinAndroidXCompose = "3.5.0"
    const val androidXNavCompose = "2.4.1"
    const val navigationCommon = "2.4.1"
    const val junit = "4.13.2"
    const val androidJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val hilt = "2.48"
    const val hiltCompiler = "1.1.0"
    const val hiltNavCompose = "1.2.0"
    const val serialization = "1.7.3"
    const val googleAuth = "20.7.0"
    const val firebaseAuth = "23.1.0"
    const val retrofit = "2.9.0"
    const val room = "2.5.2"
    const val okhttp = "4.10.0"
    const val coil = "2.2.2"
    const val androidYTPlayer = "11.1.0"
    const val coroutinesTest = "1.7.3"
    const val mockk = "1.13.5"
    const val googleTruth= "1.1.3"
    const val mockito= "4.11.0"
    const val mockitoKt= "4.1.0"


}